#!/bin/bash

function require_vscode() {
  action "code --install-extension $1"
  code --install-extension $1
  ok
}

running "Installing custom css loader"
require_vscode "be5invis.vscode-custom-css"

running "Installing vim emulation"
require_vscode "vscodevim.vim"

running "Installing eslint"
require_vscode "dbaeumer.vscode-eslint"

running "Installing prettier"
require_vscode "esbenp.prettier-vscode"

running "Installing solarized themes"
require_vscode "yogipatel.solarized-light-no-bold"
require_vscode "gerane.theme-solarized-dark"

running "Installing vim language"
require_vscode "fallenwood.viml"

bot "vscode packages installed successfully"
